server_names_hash_bucket_size 128;
resolver 127.0.0.11 valid=1s;

upstream product { server product; keepalive 10; }
upstream forum { server forum; keepalive 10; }

server {
    listen 443 ssl;
    http2 on;
    server_name captain.${HOST};
    keepalive_timeout 1;

    ssl_certificate     /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    return 403;
}

server {
    listen 443 ssl;
    http2 on;
    server_name ~^(?<subdomain>[^\.]+)\.${HOST}$;
    keepalive_timeout 1;

    ssl_certificate     /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;


    location ~* ^/call-captain {
        return 403;
    }

    location ~* ^/treasure {
        return 403;
    }

    location / {
        proxy_pass http://$subdomain$uri;
    }

}

server {
    listen 443 ssl default_server;
    http2 on;
    server_name _;
    keepalive_timeout 1;

    ssl_certificate     /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    location / {
        proxy_pass http://product$uri;
    }
}
